language: node_js

node_js:
  - "10.14.1"

sudo: true

env:
  - CXX=g++-4.8 NODE_ENV=testing
  - TOKEN_ALGORITHM=HS256
  - TOKEN_TYPE=JWT
  - TOKEN_PASS=c2VjcmV0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE bookstest;" -U postgres
  - npm run migrations-test
